joints:
  hombro:
    name: "hombro"
    odrv_serial_num: "206E3591524B"
    axis_name: "axis0"
    pos_0: 0 # TODO CHECK!!
    hardware_correction: 1.1141  # 7/(2*pi')
  codo:
    name: "codo"
    odrv_serial_num: "335D31583536"
    axis_name: "axis1"
    pos_0: 0 # TODO CHECK!!
    hardware_correction: 1.1141  # 7/(2*pi')
  z:
    name: "z"
    odrv_serial_num: "335D31583536"
    axis_name: "axis0"
    pos_0: 0 # TODO CHECK!!
    hardware_correction: 0.0625  # 1/16
dimensions:
  humero_len: 336.15
  radio_cubito_len: 338.0
  max_hombro_degree: 1.5708  # 90/180*pi
  max_codo_degree: 2.356125  # 135/180*pi
  cartesian_0:  # x, y, z for home position
    x: 0  # x
    y: 0  # y
    z: 0  # z
  orientation: "left"
